### ISSUE TITLE
Regarding installation of packages in requirement.txt

### ISSUE THREAD

**Issue by Abhinav2158** [chu0802/SLA#12]
Everytime I try to install the file requirement.txt , i am getting error ,

PackagesNotFoundError:
ERROR: Could not find a version that satisfies the requirement _packagename_ (from versions: none)
ERROR: No matching distribution found for _packagename_

How should I overcome this ?

**Comment by chu0802** [comment]
Hi, thanks for raising the issue. I am sorry for not being aware this before.
The reason is that I didn't include certain channels in my conda configuration when exporting the requirements file.

I've now updated the environment file `environment.yaml` in the main branch to include all the necessary channels. You can install the required packages by running this command
```bash
conda env create --name <ENV_NAME>  --file environment.yaml
```
Let me know if you have any further questions, thanks!

**Comment by Abhinav2158** [comment]
Thank you ,   yes i have a further doubt 

On running the model (Baseline methods and Applying SLA to baseline methods)

 everytime I am getting the same error 

RuntimeError: No CUDA GPUs are available   
So how should i overcome this ?

**Comment by chu0802** [comment]
This project requires at least one GPU to run properly. You should first make sure that the GPUs are accessible in your environment.
If packages issue has been resolved, I will close this issue later. Feel free to open a new issue for further questions, thanks!
